<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260609205020 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id VARCHAR(36) NOT NULL, action VARCHAR(50) NOT NULL, old_value JSON DEFAULT NULL, new_value JSON DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6E1C0F5A76ED395 ON audit_log (user_id)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, inn VARCHAR(12) DEFAULT NULL, kpp VARCHAR(9) DEFAULT NULL, contact_person VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(500) DEFAULT NULL, b24_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE instrument (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, model VARCHAR(255) DEFAULT NULL, serial_number VARCHAR(100) DEFAULT NULL, last_calibration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, api_endpoint VARCHAR(500) DEFAULT NULL, protocol VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE qc_sample (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, control_type VARCHAR(50) NOT NULL, expected_value DOUBLE PRECISION NOT NULL, measured_value DOUBLE PRECISION NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, test_method_id INT NOT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAE12A5E9B15AEAD ON qc_sample (test_method_id)');
        $this->addSql('CREATE INDEX IDX_CAE12A5E2D234F6A ON qc_sample (approved_by_id)');
        $this->addSql('CREATE TABLE sample (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid VARCHAR(36) NOT NULL, barcode VARCHAR(100) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata JSON DEFAULT NULL, customer_id INT DEFAULT NULL, sample_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F10B76C3D17F50A6 ON sample (uuid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F10B76C397AE0266 ON sample (barcode)');
        $this->addSql('CREATE INDEX IDX_F10B76C39395C3F3 ON sample (customer_id)');
        $this->addSql('CREATE INDEX IDX_F10B76C3D5064105 ON sample (sample_type_id)');
        $this->addSql('CREATE TABLE sample_status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_status VARCHAR(50) DEFAULT NULL, to_status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sample_id INT NOT NULL, changed_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C5E5ED51B1FEA20 ON sample_status_history (sample_id)');
        $this->addSql('CREATE INDEX IDX_4C5E5ED5828AD0A0 ON sample_status_history (changed_by_id)');
        $this->addSql('CREATE TABLE sample_test (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, result_value TEXT DEFAULT NULL, result_text TEXT DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uncertainty DOUBLE PRECISION DEFAULT NULL, qc_status VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sample_id INT NOT NULL, test_method_id INT NOT NULL, approved_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64495C411B1FEA20 ON sample_test (sample_id)');
        $this->addSql('CREATE INDEX IDX_64495C419B15AEAD ON sample_test (test_method_id)');
        $this->addSql('CREATE INDEX IDX_64495C412D234F6A ON sample_test (approved_by_id)');
        $this->addSql('CREATE TABLE sample_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE test_method (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, unit VARCHAR(50) DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, norm_min DOUBLE PRECISION DEFAULT NULL, norm_max DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C9803D4E77153098 ON test_method (code)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F5A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id)');
        $this->addSql('ALTER TABLE qc_sample ADD CONSTRAINT FK_CAE12A5E9B15AEAD FOREIGN KEY (test_method_id) REFERENCES test_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE qc_sample ADD CONSTRAINT FK_CAE12A5E2D234F6A FOREIGN KEY (approved_by_id) REFERENCES "users" (id)');
        $this->addSql('ALTER TABLE sample ADD CONSTRAINT FK_F10B76C39395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE sample ADD CONSTRAINT FK_F10B76C3D5064105 FOREIGN KEY (sample_type_id) REFERENCES sample_type (id)');
        $this->addSql('ALTER TABLE sample_status_history ADD CONSTRAINT FK_4C5E5ED51B1FEA20 FOREIGN KEY (sample_id) REFERENCES sample (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_status_history ADD CONSTRAINT FK_4C5E5ED5828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "users" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_test ADD CONSTRAINT FK_64495C411B1FEA20 FOREIGN KEY (sample_id) REFERENCES sample (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_test ADD CONSTRAINT FK_64495C419B15AEAD FOREIGN KEY (test_method_id) REFERENCES test_method (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sample_test ADD CONSTRAINT FK_64495C412D234F6A FOREIGN KEY (approved_by_id) REFERENCES "users" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5A76ED395');
        $this->addSql('ALTER TABLE qc_sample DROP CONSTRAINT FK_CAE12A5E9B15AEAD');
        $this->addSql('ALTER TABLE qc_sample DROP CONSTRAINT FK_CAE12A5E2D234F6A');
        $this->addSql('ALTER TABLE sample DROP CONSTRAINT FK_F10B76C39395C3F3');
        $this->addSql('ALTER TABLE sample DROP CONSTRAINT FK_F10B76C3D5064105');
        $this->addSql('ALTER TABLE sample_status_history DROP CONSTRAINT FK_4C5E5ED51B1FEA20');
        $this->addSql('ALTER TABLE sample_status_history DROP CONSTRAINT FK_4C5E5ED5828AD0A0');
        $this->addSql('ALTER TABLE sample_test DROP CONSTRAINT FK_64495C411B1FEA20');
        $this->addSql('ALTER TABLE sample_test DROP CONSTRAINT FK_64495C419B15AEAD');
        $this->addSql('ALTER TABLE sample_test DROP CONSTRAINT FK_64495C412D234F6A');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE instrument');
        $this->addSql('DROP TABLE qc_sample');
        $this->addSql('DROP TABLE sample');
        $this->addSql('DROP TABLE sample_status_history');
        $this->addSql('DROP TABLE sample_test');
        $this->addSql('DROP TABLE sample_type');
        $this->addSql('DROP TABLE test_method');
        $this->addSql('DROP TABLE "users"');
    }
}
